CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    first_name TEXT NOT NULL,

    last_name TEXT NOT NULL,

    email TEXT NOT NULL UNIQUE,

    password_hash TEXT NOT NULL,

    role TEXT NOT NULL DEFAULT 'CUSTOMER',

    status TEXT NOT NULL DEFAULT 'ACTIVE',

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS accounts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,

    user_id INTEGER NOT NULL,

    account_number TEXT NOT NULL UNIQUE,

    account_type TEXT NOT NULL
    CHECK(account_type IN ('SAVINGS', 'CURRENT')),

    balance REAL NOT NULL DEFAULT 0,

    currency TEXT NOT NULL DEFAULT 'INR',

    status TEXT NOT NULL
    DEFAULT 'ACTIVE'
    CHECK(status IN ('ACTIVE', 'INACTIVE', 'FROZEN', 'CLOSED')),

    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (user_id)
        REFERENCES users(id)
);

CREATE INDEX IF NOT EXISTS idx_accounts_user_id
ON accounts(user_id);